import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Download, Loader2, ArrowRight, CalendarPlus } from "lucide-react";
import { ScoreRing } from "@/components/ScoreRing";
import { getSharedGapPlan } from "@/lib/gap-plan-share.functions";
import { downloadGapPlanIcs } from "@/lib/gap-plan-ics";


export const Route = createFileRoute("/plan/$id")({
  head: () => ({
    meta: [
      { title: "Shared Skill-Gap Plan — CareerPilot AI" },
      {
        name: "description",
        content:
          "A shared AI skill-gap analysis and month-by-month improvement plan generated by CareerPilot AI.",
      },
      { property: "og:title", content: "Shared Skill-Gap Plan — CareerPilot AI" },
      {
        property: "og:description",
        content: "View a shared readiness score, prioritized skill gaps, and improvement roadmap.",
      },
      { property: "og:type", content: "article" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: SharedPlanPage,
});

const importanceStyle: Record<string, string> = {
  critical: "border-destructive/40 bg-destructive/10 text-destructive",
  important: "border-primary/40 bg-primary/10 text-primary",
  "nice-to-have": "border-border bg-secondary text-muted-foreground",
};

function SharedPlanPage() {
  const { id } = Route.useParams();
  const fetchPlan = useServerFn(getSharedGapPlan);
  const { data, isLoading, isError } = useQuery({
    queryKey: ["shared-gap-plan", id],
    queryFn: () => fetchPlan({ data: { id } }),
  });

  if (isLoading) {
    return (
      <div className="min-h-[70vh] flex items-center justify-center text-muted-foreground">
        <Loader2 className="size-5 animate-spin mr-2" /> Loading shared plan…
      </div>
    );
  }

  if (isError || !data) {
    return (
      <div className="min-h-[70vh] flex flex-col items-center justify-center gap-4 px-6 text-center">
        <h1 className="text-2xl font-semibold">This plan link isn’t available</h1>
        <p className="text-sm text-muted-foreground">The link may be invalid or the plan was deleted.</p>
        <Link to="/assessment/resume-builder" className="inline-flex items-center gap-2 rounded-xl bg-primary text-primary-foreground px-4 py-2 text-sm">
          Build your own plan <ArrowRight className="size-4" />
        </Link>
      </div>
    );
  }

  const plan = data.plan;

  return (
    <div className="mx-auto max-w-4xl px-4 md:px-6 py-10 md:py-16 space-y-6">
      <header className="space-y-2">
        <div className="text-xs uppercase tracking-widest text-muted-foreground">
          Shared skill-gap plan · {new Date(data.createdAt).toLocaleDateString()}
        </div>
        <h1 className="text-3xl md:text-4xl font-semibold">
          {data.candidateName ? `${data.candidateName} → ` : ""}
          {data.targetRole}
        </h1>
      </header>

      <div className="rounded-2xl border border-border bg-card p-6 md:p-8 flex flex-col md:flex-row items-center gap-8">
        <ScoreRing score={plan.readiness_score} label="Readiness" />
        <div className="flex-1">
          <p className="text-sm text-foreground/80 leading-relaxed">{plan.verdict}</p>
          <div className="mt-4 flex flex-wrap gap-2">
            {plan.matched_skills.map((s) => (
              <span key={s} className="text-xs rounded-full border border-border bg-secondary px-3 py-1">{s}</span>
            ))}
          </div>
          {data.pdfUrl && (
            <a
              href={data.pdfUrl}
              className="mt-5 inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2 text-sm hover:bg-secondary"
            >
              <Download className="size-4" /> Download PDF
            </a>
          )}
        </div>
      </div>

      {plan.gaps.length > 0 && (
        <div className="grid gap-4 md:grid-cols-2">
          {plan.gaps.map((g) => (
            <div key={g.skill} className="rounded-2xl border border-border bg-card p-5">
              <div className="flex items-center justify-between gap-3 mb-2">
                <div className="font-medium">{g.skill}</div>
                <div className="flex items-center gap-2">
                  {g.estimated_weeks ? (
                    <span className="text-[10px] font-mono rounded-full border border-border bg-secondary px-2 py-0.5 text-muted-foreground">
                      ~{g.estimated_weeks}w
                    </span>
                  ) : null}
                  <span className={`text-[10px] uppercase tracking-wider rounded-full border px-2 py-0.5 ${importanceStyle[g.importance] ?? importanceStyle["nice-to-have"]}`}>
                    {g.importance}
                  </span>
                </div>
              </div>
              <p className="text-xs text-muted-foreground leading-relaxed mb-2">{g.why}</p>
              <p className="text-xs text-foreground/80 leading-relaxed">{g.how}</p>
              {g.actions && g.actions.length > 0 && (
                <ul className="mt-3 space-y-2 border-t border-border pt-3">
                  {g.actions.map((a, i) => (
                    <li key={i} className="flex items-start gap-2 text-xs">
                      <span className="mt-0.5 shrink-0 rounded-full bg-primary/10 text-primary font-mono text-[10px] px-2 py-0.5">
                        {a.timeline || `Step ${i + 1}`}
                      </span>
                      <span className="text-foreground/80 leading-relaxed">{a.action}</span>
                    </li>
                  ))}
                </ul>
              )}
            </div>
          ))}
        </div>
      )}

      {plan.phases.length > 0 && (
        <div className="rounded-2xl border border-border bg-card p-6 md:p-8">
          <h2 className="text-lg font-semibold mb-5">Improvement plan</h2>
          <ol className="space-y-5 border-l border-border pl-6">
            {plan.phases.map((p) => (
              <li key={p.phase} className="relative">
                <span className="absolute -left-[31px] top-1.5 size-2.5 rounded-full bg-primary" />
                <div className="flex flex-wrap items-baseline gap-2">
                  <div className="font-medium">{p.phase}</div>
                  <div className="text-xs text-muted-foreground">{p.timeframe}</div>
                </div>
                <ul className="mt-2 space-y-1 text-sm text-foreground/80 list-disc list-inside">
                  {p.actions.map((a, i) => <li key={i}>{a}</li>)}
                </ul>
              </li>
            ))}
          </ol>
        </div>
      )}

      <div className="rounded-2xl border border-border bg-card p-6 text-center">
        <p className="text-sm text-muted-foreground mb-3">Want a plan like this for your own resume?</p>
        <Link to="/assessment/resume-builder" className="inline-flex items-center gap-2 rounded-xl bg-primary text-primary-foreground px-4 py-2 text-sm">
          Try CareerPilot AI <ArrowRight className="size-4" />
        </Link>
      </div>
    </div>
  );
}
