/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PersonalityRouteImport } from './routes/personality'
import { Route as MentorsRouteImport } from './routes/mentors'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as InternshipsRouteImport } from './routes/internships'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EmailPreviewRouteImport } from './routes/email-preview'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CareerUniverseRouteImport } from './routes/career-universe'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScholarshipsIndexRouteImport } from './routes/scholarships.index'
import { Route as RoadmapIndexRouteImport } from './routes/roadmap.index'
import { Route as MentorsIndexRouteImport } from './routes/mentors.index'
import { Route as InternshipsIndexRouteImport } from './routes/internships.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AssessmentIndexRouteImport } from './routes/assessment.index'
import { Route as StreamIdRouteImport } from './routes/stream.$id'
import { Route as ScholarshipsNeedRouteImport } from './routes/scholarships.need'
import { Route as ScholarshipsMeritRouteImport } from './routes/scholarships.merit'
import { Route as ScholarshipsDiversityRouteImport } from './routes/scholarships.diversity'
import { Route as ScholarshipsBrowseRouteImport } from './routes/scholarships.browse'
import { Route as ScholarshipsAbroadRouteImport } from './routes/scholarships.abroad'
import { Route as RoadmapTechRouteImport } from './routes/roadmap.tech'
import { Route as RoadmapResourcesRouteImport } from './routes/roadmap.resources'
import { Route as RoadmapMilestonesRouteImport } from './routes/roadmap.milestones'
import { Route as RoadmapCreativeRouteImport } from './routes/roadmap.creative'
import { Route as RoadmapBusinessRouteImport } from './routes/roadmap.business'
import { Route as RoadmapAiRouteImport } from './routes/roadmap.ai'
import { Route as PlanIdRouteImport } from './routes/plan.$id'
import { Route as MentorsTopRouteImport } from './routes/mentors.top'
import { Route as MentorsSessionsRouteImport } from './routes/mentors.sessions'
import { Route as MentorsFindRouteImport } from './routes/mentors.find'
import { Route as MentorsBookRouteImport } from './routes/mentors.book'
import { Route as MentorsBecomeRouteImport } from './routes/mentors.become'
import { Route as InternshipsSummerRouteImport } from './routes/internships.summer'
import { Route as InternshipsStartupRouteImport } from './routes/internships.startup'
import { Route as InternshipsRemoteRouteImport } from './routes/internships.remote'
import { Route as InternshipsPrepRouteImport } from './routes/internships.prep'
import { Route as InternshipsCorporateRouteImport } from './routes/internships.corporate'
import { Route as DomainSlugRouteImport } from './routes/domain.$slug'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardSavedRouteImport } from './routes/dashboard.saved'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardBadgesRouteImport } from './routes/dashboard.badges'
import { Route as DashboardApplicationsRouteImport } from './routes/dashboard.applications'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as CareerSlugRouteImport } from './routes/career.$slug'
import { Route as BlogStoriesRouteImport } from './routes/blog.stories'
import { Route as BlogNewsRouteImport } from './routes/blog.news'
import { Route as BlogAdviceRouteImport } from './routes/blog.advice'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AssessmentTechnicalRouteImport } from './routes/assessment.technical'
import { Route as AssessmentResumeBuilderRouteImport } from './routes/assessment.resume-builder'
import { Route as AssessmentResumeRouteImport } from './routes/assessment.resume'
import { Route as AssessmentPersonalityRouteImport } from './routes/assessment.personality'
import { Route as AssessmentMockInterviewRouteImport } from './routes/assessment.mock-interview'
import { Route as AssessmentInterviewRouteImport } from './routes/assessment.interview'
import { Route as AssessmentCareerFitRouteImport } from './routes/assessment.career-fit'
import { Route as AssessmentAptitudeRouteImport } from './routes/assessment.aptitude'
import { Route as ApplyJobIdRouteImport } from './routes/apply.$jobId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalityRoute = PersonalityRouteImport.update({
  id: '/personality',
  path: '/personality',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsRoute = MentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsRoute = InternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailPreviewRoute = EmailPreviewRouteImport.update({
  id: '/email-preview',
  path: '/email-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerUniverseRoute = CareerUniverseRouteImport.update({
  id: '/career-universe',
  path: '/career-universe',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsIndexRoute = ScholarshipsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScholarshipsRoute,
} as any)
const RoadmapIndexRoute = RoadmapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RoadmapRoute,
} as any)
const MentorsIndexRoute = MentorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MentorsRoute,
} as any)
const InternshipsIndexRoute = InternshipsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InternshipsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AssessmentIndexRoute = AssessmentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AssessmentRoute,
} as any)
const StreamIdRoute = StreamIdRouteImport.update({
  id: '/stream/$id',
  path: '/stream/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsNeedRoute = ScholarshipsNeedRouteImport.update({
  id: '/need',
  path: '/need',
  getParentRoute: () => ScholarshipsRoute,
} as any)
const ScholarshipsMeritRoute = ScholarshipsMeritRouteImport.update({
  id: '/merit',
  path: '/merit',
  getParentRoute: () => ScholarshipsRoute,
} as any)
const ScholarshipsDiversityRoute = ScholarshipsDiversityRouteImport.update({
  id: '/diversity',
  path: '/diversity',
  getParentRoute: () => ScholarshipsRoute,
} as any)
const ScholarshipsBrowseRoute = ScholarshipsBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => ScholarshipsRoute,
} as any)
const ScholarshipsAbroadRoute = ScholarshipsAbroadRouteImport.update({
  id: '/abroad',
  path: '/abroad',
  getParentRoute: () => ScholarshipsRoute,
} as any)
const RoadmapTechRoute = RoadmapTechRouteImport.update({
  id: '/tech',
  path: '/tech',
  getParentRoute: () => RoadmapRoute,
} as any)
const RoadmapResourcesRoute = RoadmapResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => RoadmapRoute,
} as any)
const RoadmapMilestonesRoute = RoadmapMilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => RoadmapRoute,
} as any)
const RoadmapCreativeRoute = RoadmapCreativeRouteImport.update({
  id: '/creative',
  path: '/creative',
  getParentRoute: () => RoadmapRoute,
} as any)
const RoadmapBusinessRoute = RoadmapBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => RoadmapRoute,
} as any)
const RoadmapAiRoute = RoadmapAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => RoadmapRoute,
} as any)
const PlanIdRoute = PlanIdRouteImport.update({
  id: '/plan/$id',
  path: '/plan/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorsTopRoute = MentorsTopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => MentorsRoute,
} as any)
const MentorsSessionsRoute = MentorsSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => MentorsRoute,
} as any)
const MentorsFindRoute = MentorsFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => MentorsRoute,
} as any)
const MentorsBookRoute = MentorsBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => MentorsRoute,
} as any)
const MentorsBecomeRoute = MentorsBecomeRouteImport.update({
  id: '/become',
  path: '/become',
  getParentRoute: () => MentorsRoute,
} as any)
const InternshipsSummerRoute = InternshipsSummerRouteImport.update({
  id: '/summer',
  path: '/summer',
  getParentRoute: () => InternshipsRoute,
} as any)
const InternshipsStartupRoute = InternshipsStartupRouteImport.update({
  id: '/startup',
  path: '/startup',
  getParentRoute: () => InternshipsRoute,
} as any)
const InternshipsRemoteRoute = InternshipsRemoteRouteImport.update({
  id: '/remote',
  path: '/remote',
  getParentRoute: () => InternshipsRoute,
} as any)
const InternshipsPrepRoute = InternshipsPrepRouteImport.update({
  id: '/prep',
  path: '/prep',
  getParentRoute: () => InternshipsRoute,
} as any)
const InternshipsCorporateRoute = InternshipsCorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => InternshipsRoute,
} as any)
const DomainSlugRoute = DomainSlugRouteImport.update({
  id: '/domain/$slug',
  path: '/domain/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSavedRoute = DashboardSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBadgesRoute = DashboardBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplicationsRoute = DashboardApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const CareerSlugRoute = CareerSlugRouteImport.update({
  id: '/career/$slug',
  path: '/career/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogStoriesRoute = BlogStoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => BlogRoute,
} as any)
const BlogNewsRoute = BlogNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => BlogRoute,
} as any)
const BlogAdviceRoute = BlogAdviceRouteImport.update({
  id: '/advice',
  path: '/advice',
  getParentRoute: () => BlogRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentTechnicalRoute = AssessmentTechnicalRouteImport.update({
  id: '/technical',
  path: '/technical',
  getParentRoute: () => AssessmentRoute,
} as any)
const AssessmentResumeBuilderRoute = AssessmentResumeBuilderRouteImport.update({
  id: '/resume-builder',
  path: '/resume-builder',
  getParentRoute: () => AssessmentRoute,
} as any)
const AssessmentResumeRoute = AssessmentResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AssessmentRoute,
} as any)
const AssessmentPersonalityRoute = AssessmentPersonalityRouteImport.update({
  id: '/personality',
  path: '/personality',
  getParentRoute: () => AssessmentRoute,
} as any)
const AssessmentMockInterviewRoute = AssessmentMockInterviewRouteImport.update({
  id: '/mock-interview',
  path: '/mock-interview',
  getParentRoute: () => AssessmentRoute,
} as any)
const AssessmentInterviewRoute = AssessmentInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AssessmentRoute,
} as any)
const AssessmentCareerFitRoute = AssessmentCareerFitRouteImport.update({
  id: '/career-fit',
  path: '/career-fit',
  getParentRoute: () => AssessmentRoute,
} as any)
const AssessmentAptitudeRoute = AssessmentAptitudeRouteImport.update({
  id: '/aptitude',
  path: '/aptitude',
  getParentRoute: () => AssessmentRoute,
} as any)
const ApplyJobIdRoute = ApplyJobIdRouteImport.update({
  id: '/apply/$jobId',
  path: '/apply/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/assessment': typeof AssessmentRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/career-universe': typeof CareerUniverseRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/email-preview': typeof EmailPreviewRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/internships': typeof InternshipsRouteWithChildren
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/mentors': typeof MentorsRouteWithChildren
  '/personality': typeof PersonalityRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRouteWithChildren
  '/scholarships': typeof ScholarshipsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/workspace': typeof WorkspaceRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/assessment/aptitude': typeof AssessmentAptitudeRoute
  '/assessment/career-fit': typeof AssessmentCareerFitRoute
  '/assessment/interview': typeof AssessmentInterviewRoute
  '/assessment/mock-interview': typeof AssessmentMockInterviewRoute
  '/assessment/personality': typeof AssessmentPersonalityRoute
  '/assessment/resume': typeof AssessmentResumeRoute
  '/assessment/resume-builder': typeof AssessmentResumeBuilderRoute
  '/assessment/technical': typeof AssessmentTechnicalRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/advice': typeof BlogAdviceRoute
  '/blog/news': typeof BlogNewsRoute
  '/blog/stories': typeof BlogStoriesRoute
  '/career/$slug': typeof CareerSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/badges': typeof DashboardBadgesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/domain/$slug': typeof DomainSlugRoute
  '/internships/corporate': typeof InternshipsCorporateRoute
  '/internships/prep': typeof InternshipsPrepRoute
  '/internships/remote': typeof InternshipsRemoteRoute
  '/internships/startup': typeof InternshipsStartupRoute
  '/internships/summer': typeof InternshipsSummerRoute
  '/mentors/become': typeof MentorsBecomeRoute
  '/mentors/book': typeof MentorsBookRoute
  '/mentors/find': typeof MentorsFindRoute
  '/mentors/sessions': typeof MentorsSessionsRoute
  '/mentors/top': typeof MentorsTopRoute
  '/plan/$id': typeof PlanIdRoute
  '/roadmap/ai': typeof RoadmapAiRoute
  '/roadmap/business': typeof RoadmapBusinessRoute
  '/roadmap/creative': typeof RoadmapCreativeRoute
  '/roadmap/milestones': typeof RoadmapMilestonesRoute
  '/roadmap/resources': typeof RoadmapResourcesRoute
  '/roadmap/tech': typeof RoadmapTechRoute
  '/scholarships/abroad': typeof ScholarshipsAbroadRoute
  '/scholarships/browse': typeof ScholarshipsBrowseRoute
  '/scholarships/diversity': typeof ScholarshipsDiversityRoute
  '/scholarships/merit': typeof ScholarshipsMeritRoute
  '/scholarships/need': typeof ScholarshipsNeedRoute
  '/stream/$id': typeof StreamIdRoute
  '/assessment/': typeof AssessmentIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/internships/': typeof InternshipsIndexRoute
  '/mentors/': typeof MentorsIndexRoute
  '/roadmap/': typeof RoadmapIndexRoute
  '/scholarships/': typeof ScholarshipsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/career-universe': typeof CareerUniverseRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/email-preview': typeof EmailPreviewRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/personality': typeof PersonalityRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/resume': typeof ResumeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/workspace': typeof WorkspaceRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/assessment/aptitude': typeof AssessmentAptitudeRoute
  '/assessment/career-fit': typeof AssessmentCareerFitRoute
  '/assessment/interview': typeof AssessmentInterviewRoute
  '/assessment/mock-interview': typeof AssessmentMockInterviewRoute
  '/assessment/personality': typeof AssessmentPersonalityRoute
  '/assessment/resume': typeof AssessmentResumeRoute
  '/assessment/resume-builder': typeof AssessmentResumeBuilderRoute
  '/assessment/technical': typeof AssessmentTechnicalRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/advice': typeof BlogAdviceRoute
  '/blog/news': typeof BlogNewsRoute
  '/blog/stories': typeof BlogStoriesRoute
  '/career/$slug': typeof CareerSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/badges': typeof DashboardBadgesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/domain/$slug': typeof DomainSlugRoute
  '/internships/corporate': typeof InternshipsCorporateRoute
  '/internships/prep': typeof InternshipsPrepRoute
  '/internships/remote': typeof InternshipsRemoteRoute
  '/internships/startup': typeof InternshipsStartupRoute
  '/internships/summer': typeof InternshipsSummerRoute
  '/mentors/become': typeof MentorsBecomeRoute
  '/mentors/book': typeof MentorsBookRoute
  '/mentors/find': typeof MentorsFindRoute
  '/mentors/sessions': typeof MentorsSessionsRoute
  '/mentors/top': typeof MentorsTopRoute
  '/plan/$id': typeof PlanIdRoute
  '/roadmap/ai': typeof RoadmapAiRoute
  '/roadmap/business': typeof RoadmapBusinessRoute
  '/roadmap/creative': typeof RoadmapCreativeRoute
  '/roadmap/milestones': typeof RoadmapMilestonesRoute
  '/roadmap/resources': typeof RoadmapResourcesRoute
  '/roadmap/tech': typeof RoadmapTechRoute
  '/scholarships/abroad': typeof ScholarshipsAbroadRoute
  '/scholarships/browse': typeof ScholarshipsBrowseRoute
  '/scholarships/diversity': typeof ScholarshipsDiversityRoute
  '/scholarships/merit': typeof ScholarshipsMeritRoute
  '/scholarships/need': typeof ScholarshipsNeedRoute
  '/stream/$id': typeof StreamIdRoute
  '/assessment': typeof AssessmentIndexRoute
  '/blog': typeof BlogIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/internships': typeof InternshipsIndexRoute
  '/mentors': typeof MentorsIndexRoute
  '/roadmap': typeof RoadmapIndexRoute
  '/scholarships': typeof ScholarshipsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/assessment': typeof AssessmentRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/career-universe': typeof CareerUniverseRoute
  '/compare': typeof CompareRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/email-preview': typeof EmailPreviewRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/internships': typeof InternshipsRouteWithChildren
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/mentors': typeof MentorsRouteWithChildren
  '/personality': typeof PersonalityRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRouteWithChildren
  '/scholarships': typeof ScholarshipsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skills': typeof SkillsRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/workspace': typeof WorkspaceRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/apply/$jobId': typeof ApplyJobIdRoute
  '/assessment/aptitude': typeof AssessmentAptitudeRoute
  '/assessment/career-fit': typeof AssessmentCareerFitRoute
  '/assessment/interview': typeof AssessmentInterviewRoute
  '/assessment/mock-interview': typeof AssessmentMockInterviewRoute
  '/assessment/personality': typeof AssessmentPersonalityRoute
  '/assessment/resume': typeof AssessmentResumeRoute
  '/assessment/resume-builder': typeof AssessmentResumeBuilderRoute
  '/assessment/technical': typeof AssessmentTechnicalRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/advice': typeof BlogAdviceRoute
  '/blog/news': typeof BlogNewsRoute
  '/blog/stories': typeof BlogStoriesRoute
  '/career/$slug': typeof CareerSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/badges': typeof DashboardBadgesRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/saved': typeof DashboardSavedRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/domain/$slug': typeof DomainSlugRoute
  '/internships/corporate': typeof InternshipsCorporateRoute
  '/internships/prep': typeof InternshipsPrepRoute
  '/internships/remote': typeof InternshipsRemoteRoute
  '/internships/startup': typeof InternshipsStartupRoute
  '/internships/summer': typeof InternshipsSummerRoute
  '/mentors/become': typeof MentorsBecomeRoute
  '/mentors/book': typeof MentorsBookRoute
  '/mentors/find': typeof MentorsFindRoute
  '/mentors/sessions': typeof MentorsSessionsRoute
  '/mentors/top': typeof MentorsTopRoute
  '/plan/$id': typeof PlanIdRoute
  '/roadmap/ai': typeof RoadmapAiRoute
  '/roadmap/business': typeof RoadmapBusinessRoute
  '/roadmap/creative': typeof RoadmapCreativeRoute
  '/roadmap/milestones': typeof RoadmapMilestonesRoute
  '/roadmap/resources': typeof RoadmapResourcesRoute
  '/roadmap/tech': typeof RoadmapTechRoute
  '/scholarships/abroad': typeof ScholarshipsAbroadRoute
  '/scholarships/browse': typeof ScholarshipsBrowseRoute
  '/scholarships/diversity': typeof ScholarshipsDiversityRoute
  '/scholarships/merit': typeof ScholarshipsMeritRoute
  '/scholarships/need': typeof ScholarshipsNeedRoute
  '/stream/$id': typeof StreamIdRoute
  '/assessment/': typeof AssessmentIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/internships/': typeof InternshipsIndexRoute
  '/mentors/': typeof MentorsIndexRoute
  '/roadmap/': typeof RoadmapIndexRoute
  '/scholarships/': typeof ScholarshipsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/assessment'
    | '/blog'
    | '/career-universe'
    | '/compare'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/email-preview'
    | '/faq'
    | '/features'
    | '/how-it-works'
    | '/internships'
    | '/jobs'
    | '/login'
    | '/mcp'
    | '/mentors'
    | '/personality'
    | '/pricing'
    | '/profile'
    | '/reset-password'
    | '/resources'
    | '/resume'
    | '/roadmap'
    | '/scholarships'
    | '/sitemap.xml'
    | '/skills'
    | '/success-stories'
    | '/workspace'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/apply/$jobId'
    | '/assessment/aptitude'
    | '/assessment/career-fit'
    | '/assessment/interview'
    | '/assessment/mock-interview'
    | '/assessment/personality'
    | '/assessment/resume'
    | '/assessment/resume-builder'
    | '/assessment/technical'
    | '/auth/callback'
    | '/blog/advice'
    | '/blog/news'
    | '/blog/stories'
    | '/career/$slug'
    | '/dashboard/analytics'
    | '/dashboard/applications'
    | '/dashboard/badges'
    | '/dashboard/profile'
    | '/dashboard/saved'
    | '/dashboard/settings'
    | '/domain/$slug'
    | '/internships/corporate'
    | '/internships/prep'
    | '/internships/remote'
    | '/internships/startup'
    | '/internships/summer'
    | '/mentors/become'
    | '/mentors/book'
    | '/mentors/find'
    | '/mentors/sessions'
    | '/mentors/top'
    | '/plan/$id'
    | '/roadmap/ai'
    | '/roadmap/business'
    | '/roadmap/creative'
    | '/roadmap/milestones'
    | '/roadmap/resources'
    | '/roadmap/tech'
    | '/scholarships/abroad'
    | '/scholarships/browse'
    | '/scholarships/diversity'
    | '/scholarships/merit'
    | '/scholarships/need'
    | '/stream/$id'
    | '/assessment/'
    | '/blog/'
    | '/dashboard/'
    | '/internships/'
    | '/mentors/'
    | '/roadmap/'
    | '/scholarships/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/career-universe'
    | '/compare'
    | '/contact'
    | '/courses'
    | '/email-preview'
    | '/faq'
    | '/features'
    | '/how-it-works'
    | '/jobs'
    | '/login'
    | '/mcp'
    | '/personality'
    | '/pricing'
    | '/profile'
    | '/reset-password'
    | '/resources'
    | '/resume'
    | '/sitemap.xml'
    | '/skills'
    | '/success-stories'
    | '/workspace'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/apply/$jobId'
    | '/assessment/aptitude'
    | '/assessment/career-fit'
    | '/assessment/interview'
    | '/assessment/mock-interview'
    | '/assessment/personality'
    | '/assessment/resume'
    | '/assessment/resume-builder'
    | '/assessment/technical'
    | '/auth/callback'
    | '/blog/advice'
    | '/blog/news'
    | '/blog/stories'
    | '/career/$slug'
    | '/dashboard/analytics'
    | '/dashboard/applications'
    | '/dashboard/badges'
    | '/dashboard/profile'
    | '/dashboard/saved'
    | '/dashboard/settings'
    | '/domain/$slug'
    | '/internships/corporate'
    | '/internships/prep'
    | '/internships/remote'
    | '/internships/startup'
    | '/internships/summer'
    | '/mentors/become'
    | '/mentors/book'
    | '/mentors/find'
    | '/mentors/sessions'
    | '/mentors/top'
    | '/plan/$id'
    | '/roadmap/ai'
    | '/roadmap/business'
    | '/roadmap/creative'
    | '/roadmap/milestones'
    | '/roadmap/resources'
    | '/roadmap/tech'
    | '/scholarships/abroad'
    | '/scholarships/browse'
    | '/scholarships/diversity'
    | '/scholarships/merit'
    | '/scholarships/need'
    | '/stream/$id'
    | '/assessment'
    | '/blog'
    | '/dashboard'
    | '/internships'
    | '/mentors'
    | '/roadmap'
    | '/scholarships'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/assessment'
    | '/blog'
    | '/career-universe'
    | '/compare'
    | '/contact'
    | '/courses'
    | '/dashboard'
    | '/email-preview'
    | '/faq'
    | '/features'
    | '/how-it-works'
    | '/internships'
    | '/jobs'
    | '/login'
    | '/mcp'
    | '/mentors'
    | '/personality'
    | '/pricing'
    | '/profile'
    | '/reset-password'
    | '/resources'
    | '/resume'
    | '/roadmap'
    | '/scholarships'
    | '/sitemap.xml'
    | '/skills'
    | '/success-stories'
    | '/workspace'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/apply/$jobId'
    | '/assessment/aptitude'
    | '/assessment/career-fit'
    | '/assessment/interview'
    | '/assessment/mock-interview'
    | '/assessment/personality'
    | '/assessment/resume'
    | '/assessment/resume-builder'
    | '/assessment/technical'
    | '/auth/callback'
    | '/blog/advice'
    | '/blog/news'
    | '/blog/stories'
    | '/career/$slug'
    | '/dashboard/analytics'
    | '/dashboard/applications'
    | '/dashboard/badges'
    | '/dashboard/profile'
    | '/dashboard/saved'
    | '/dashboard/settings'
    | '/domain/$slug'
    | '/internships/corporate'
    | '/internships/prep'
    | '/internships/remote'
    | '/internships/startup'
    | '/internships/summer'
    | '/mentors/become'
    | '/mentors/book'
    | '/mentors/find'
    | '/mentors/sessions'
    | '/mentors/top'
    | '/plan/$id'
    | '/roadmap/ai'
    | '/roadmap/business'
    | '/roadmap/creative'
    | '/roadmap/milestones'
    | '/roadmap/resources'
    | '/roadmap/tech'
    | '/scholarships/abroad'
    | '/scholarships/browse'
    | '/scholarships/diversity'
    | '/scholarships/merit'
    | '/scholarships/need'
    | '/stream/$id'
    | '/assessment/'
    | '/blog/'
    | '/dashboard/'
    | '/internships/'
    | '/mentors/'
    | '/roadmap/'
    | '/scholarships/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AssessmentRoute: typeof AssessmentRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CareerUniverseRoute: typeof CareerUniverseRoute
  CompareRoute: typeof CompareRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EmailPreviewRoute: typeof EmailPreviewRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  InternshipsRoute: typeof InternshipsRouteWithChildren
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  MentorsRoute: typeof MentorsRouteWithChildren
  PersonalityRoute: typeof PersonalityRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  ResumeRoute: typeof ResumeRoute
  RoadmapRoute: typeof RoadmapRouteWithChildren
  ScholarshipsRoute: typeof ScholarshipsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkillsRoute: typeof SkillsRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  WorkspaceRoute: typeof WorkspaceRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApplyJobIdRoute: typeof ApplyJobIdRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CareerSlugRoute: typeof CareerSlugRoute
  DomainSlugRoute: typeof DomainSlugRoute
  PlanIdRoute: typeof PlanIdRoute
  StreamIdRoute: typeof StreamIdRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personality': {
      id: '/personality'
      path: '/personality'
      fullPath: '/personality'
      preLoaderRoute: typeof PersonalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors': {
      id: '/mentors'
      path: '/mentors'
      fullPath: '/mentors'
      preLoaderRoute: typeof MentorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships': {
      id: '/internships'
      path: '/internships'
      fullPath: '/internships'
      preLoaderRoute: typeof InternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-preview': {
      id: '/email-preview'
      path: '/email-preview'
      fullPath: '/email-preview'
      preLoaderRoute: typeof EmailPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-universe': {
      id: '/career-universe'
      path: '/career-universe'
      fullPath: '/career-universe'
      preLoaderRoute: typeof CareerUniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships/': {
      id: '/scholarships/'
      path: '/'
      fullPath: '/scholarships/'
      preLoaderRoute: typeof ScholarshipsIndexRouteImport
      parentRoute: typeof ScholarshipsRoute
    }
    '/roadmap/': {
      id: '/roadmap/'
      path: '/'
      fullPath: '/roadmap/'
      preLoaderRoute: typeof RoadmapIndexRouteImport
      parentRoute: typeof RoadmapRoute
    }
    '/mentors/': {
      id: '/mentors/'
      path: '/'
      fullPath: '/mentors/'
      preLoaderRoute: typeof MentorsIndexRouteImport
      parentRoute: typeof MentorsRoute
    }
    '/internships/': {
      id: '/internships/'
      path: '/'
      fullPath: '/internships/'
      preLoaderRoute: typeof InternshipsIndexRouteImport
      parentRoute: typeof InternshipsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/assessment/': {
      id: '/assessment/'
      path: '/'
      fullPath: '/assessment/'
      preLoaderRoute: typeof AssessmentIndexRouteImport
      parentRoute: typeof AssessmentRoute
    }
    '/stream/$id': {
      id: '/stream/$id'
      path: '/stream/$id'
      fullPath: '/stream/$id'
      preLoaderRoute: typeof StreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships/need': {
      id: '/scholarships/need'
      path: '/need'
      fullPath: '/scholarships/need'
      preLoaderRoute: typeof ScholarshipsNeedRouteImport
      parentRoute: typeof ScholarshipsRoute
    }
    '/scholarships/merit': {
      id: '/scholarships/merit'
      path: '/merit'
      fullPath: '/scholarships/merit'
      preLoaderRoute: typeof ScholarshipsMeritRouteImport
      parentRoute: typeof ScholarshipsRoute
    }
    '/scholarships/diversity': {
      id: '/scholarships/diversity'
      path: '/diversity'
      fullPath: '/scholarships/diversity'
      preLoaderRoute: typeof ScholarshipsDiversityRouteImport
      parentRoute: typeof ScholarshipsRoute
    }
    '/scholarships/browse': {
      id: '/scholarships/browse'
      path: '/browse'
      fullPath: '/scholarships/browse'
      preLoaderRoute: typeof ScholarshipsBrowseRouteImport
      parentRoute: typeof ScholarshipsRoute
    }
    '/scholarships/abroad': {
      id: '/scholarships/abroad'
      path: '/abroad'
      fullPath: '/scholarships/abroad'
      preLoaderRoute: typeof ScholarshipsAbroadRouteImport
      parentRoute: typeof ScholarshipsRoute
    }
    '/roadmap/tech': {
      id: '/roadmap/tech'
      path: '/tech'
      fullPath: '/roadmap/tech'
      preLoaderRoute: typeof RoadmapTechRouteImport
      parentRoute: typeof RoadmapRoute
    }
    '/roadmap/resources': {
      id: '/roadmap/resources'
      path: '/resources'
      fullPath: '/roadmap/resources'
      preLoaderRoute: typeof RoadmapResourcesRouteImport
      parentRoute: typeof RoadmapRoute
    }
    '/roadmap/milestones': {
      id: '/roadmap/milestones'
      path: '/milestones'
      fullPath: '/roadmap/milestones'
      preLoaderRoute: typeof RoadmapMilestonesRouteImport
      parentRoute: typeof RoadmapRoute
    }
    '/roadmap/creative': {
      id: '/roadmap/creative'
      path: '/creative'
      fullPath: '/roadmap/creative'
      preLoaderRoute: typeof RoadmapCreativeRouteImport
      parentRoute: typeof RoadmapRoute
    }
    '/roadmap/business': {
      id: '/roadmap/business'
      path: '/business'
      fullPath: '/roadmap/business'
      preLoaderRoute: typeof RoadmapBusinessRouteImport
      parentRoute: typeof RoadmapRoute
    }
    '/roadmap/ai': {
      id: '/roadmap/ai'
      path: '/ai'
      fullPath: '/roadmap/ai'
      preLoaderRoute: typeof RoadmapAiRouteImport
      parentRoute: typeof RoadmapRoute
    }
    '/plan/$id': {
      id: '/plan/$id'
      path: '/plan/$id'
      fullPath: '/plan/$id'
      preLoaderRoute: typeof PlanIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentors/top': {
      id: '/mentors/top'
      path: '/top'
      fullPath: '/mentors/top'
      preLoaderRoute: typeof MentorsTopRouteImport
      parentRoute: typeof MentorsRoute
    }
    '/mentors/sessions': {
      id: '/mentors/sessions'
      path: '/sessions'
      fullPath: '/mentors/sessions'
      preLoaderRoute: typeof MentorsSessionsRouteImport
      parentRoute: typeof MentorsRoute
    }
    '/mentors/find': {
      id: '/mentors/find'
      path: '/find'
      fullPath: '/mentors/find'
      preLoaderRoute: typeof MentorsFindRouteImport
      parentRoute: typeof MentorsRoute
    }
    '/mentors/book': {
      id: '/mentors/book'
      path: '/book'
      fullPath: '/mentors/book'
      preLoaderRoute: typeof MentorsBookRouteImport
      parentRoute: typeof MentorsRoute
    }
    '/mentors/become': {
      id: '/mentors/become'
      path: '/become'
      fullPath: '/mentors/become'
      preLoaderRoute: typeof MentorsBecomeRouteImport
      parentRoute: typeof MentorsRoute
    }
    '/internships/summer': {
      id: '/internships/summer'
      path: '/summer'
      fullPath: '/internships/summer'
      preLoaderRoute: typeof InternshipsSummerRouteImport
      parentRoute: typeof InternshipsRoute
    }
    '/internships/startup': {
      id: '/internships/startup'
      path: '/startup'
      fullPath: '/internships/startup'
      preLoaderRoute: typeof InternshipsStartupRouteImport
      parentRoute: typeof InternshipsRoute
    }
    '/internships/remote': {
      id: '/internships/remote'
      path: '/remote'
      fullPath: '/internships/remote'
      preLoaderRoute: typeof InternshipsRemoteRouteImport
      parentRoute: typeof InternshipsRoute
    }
    '/internships/prep': {
      id: '/internships/prep'
      path: '/prep'
      fullPath: '/internships/prep'
      preLoaderRoute: typeof InternshipsPrepRouteImport
      parentRoute: typeof InternshipsRoute
    }
    '/internships/corporate': {
      id: '/internships/corporate'
      path: '/corporate'
      fullPath: '/internships/corporate'
      preLoaderRoute: typeof InternshipsCorporateRouteImport
      parentRoute: typeof InternshipsRoute
    }
    '/domain/$slug': {
      id: '/domain/$slug'
      path: '/domain/$slug'
      fullPath: '/domain/$slug'
      preLoaderRoute: typeof DomainSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/saved': {
      id: '/dashboard/saved'
      path: '/saved'
      fullPath: '/dashboard/saved'
      preLoaderRoute: typeof DashboardSavedRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/badges': {
      id: '/dashboard/badges'
      path: '/badges'
      fullPath: '/dashboard/badges'
      preLoaderRoute: typeof DashboardBadgesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/applications': {
      id: '/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof DashboardApplicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/career/$slug': {
      id: '/career/$slug'
      path: '/career/$slug'
      fullPath: '/career/$slug'
      preLoaderRoute: typeof CareerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/stories': {
      id: '/blog/stories'
      path: '/stories'
      fullPath: '/blog/stories'
      preLoaderRoute: typeof BlogStoriesRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/news': {
      id: '/blog/news'
      path: '/news'
      fullPath: '/blog/news'
      preLoaderRoute: typeof BlogNewsRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/advice': {
      id: '/blog/advice'
      path: '/advice'
      fullPath: '/blog/advice'
      preLoaderRoute: typeof BlogAdviceRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/technical': {
      id: '/assessment/technical'
      path: '/technical'
      fullPath: '/assessment/technical'
      preLoaderRoute: typeof AssessmentTechnicalRouteImport
      parentRoute: typeof AssessmentRoute
    }
    '/assessment/resume-builder': {
      id: '/assessment/resume-builder'
      path: '/resume-builder'
      fullPath: '/assessment/resume-builder'
      preLoaderRoute: typeof AssessmentResumeBuilderRouteImport
      parentRoute: typeof AssessmentRoute
    }
    '/assessment/resume': {
      id: '/assessment/resume'
      path: '/resume'
      fullPath: '/assessment/resume'
      preLoaderRoute: typeof AssessmentResumeRouteImport
      parentRoute: typeof AssessmentRoute
    }
    '/assessment/personality': {
      id: '/assessment/personality'
      path: '/personality'
      fullPath: '/assessment/personality'
      preLoaderRoute: typeof AssessmentPersonalityRouteImport
      parentRoute: typeof AssessmentRoute
    }
    '/assessment/mock-interview': {
      id: '/assessment/mock-interview'
      path: '/mock-interview'
      fullPath: '/assessment/mock-interview'
      preLoaderRoute: typeof AssessmentMockInterviewRouteImport
      parentRoute: typeof AssessmentRoute
    }
    '/assessment/interview': {
      id: '/assessment/interview'
      path: '/interview'
      fullPath: '/assessment/interview'
      preLoaderRoute: typeof AssessmentInterviewRouteImport
      parentRoute: typeof AssessmentRoute
    }
    '/assessment/career-fit': {
      id: '/assessment/career-fit'
      path: '/career-fit'
      fullPath: '/assessment/career-fit'
      preLoaderRoute: typeof AssessmentCareerFitRouteImport
      parentRoute: typeof AssessmentRoute
    }
    '/assessment/aptitude': {
      id: '/assessment/aptitude'
      path: '/aptitude'
      fullPath: '/assessment/aptitude'
      preLoaderRoute: typeof AssessmentAptitudeRouteImport
      parentRoute: typeof AssessmentRoute
    }
    '/apply/$jobId': {
      id: '/apply/$jobId'
      path: '/apply/$jobId'
      fullPath: '/apply/$jobId'
      preLoaderRoute: typeof ApplyJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AssessmentRouteChildren {
  AssessmentAptitudeRoute: typeof AssessmentAptitudeRoute
  AssessmentCareerFitRoute: typeof AssessmentCareerFitRoute
  AssessmentInterviewRoute: typeof AssessmentInterviewRoute
  AssessmentMockInterviewRoute: typeof AssessmentMockInterviewRoute
  AssessmentPersonalityRoute: typeof AssessmentPersonalityRoute
  AssessmentResumeRoute: typeof AssessmentResumeRoute
  AssessmentResumeBuilderRoute: typeof AssessmentResumeBuilderRoute
  AssessmentTechnicalRoute: typeof AssessmentTechnicalRoute
  AssessmentIndexRoute: typeof AssessmentIndexRoute
}

const AssessmentRouteChildren: AssessmentRouteChildren = {
  AssessmentAptitudeRoute: AssessmentAptitudeRoute,
  AssessmentCareerFitRoute: AssessmentCareerFitRoute,
  AssessmentInterviewRoute: AssessmentInterviewRoute,
  AssessmentMockInterviewRoute: AssessmentMockInterviewRoute,
  AssessmentPersonalityRoute: AssessmentPersonalityRoute,
  AssessmentResumeRoute: AssessmentResumeRoute,
  AssessmentResumeBuilderRoute: AssessmentResumeBuilderRoute,
  AssessmentTechnicalRoute: AssessmentTechnicalRoute,
  AssessmentIndexRoute: AssessmentIndexRoute,
}

const AssessmentRouteWithChildren = AssessmentRoute._addFileChildren(
  AssessmentRouteChildren,
)

interface BlogRouteChildren {
  BlogAdviceRoute: typeof BlogAdviceRoute
  BlogNewsRoute: typeof BlogNewsRoute
  BlogStoriesRoute: typeof BlogStoriesRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogAdviceRoute: BlogAdviceRoute,
  BlogNewsRoute: BlogNewsRoute,
  BlogStoriesRoute: BlogStoriesRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardApplicationsRoute: typeof DashboardApplicationsRoute
  DashboardBadgesRoute: typeof DashboardBadgesRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSavedRoute: typeof DashboardSavedRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardApplicationsRoute: DashboardApplicationsRoute,
  DashboardBadgesRoute: DashboardBadgesRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSavedRoute: DashboardSavedRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface InternshipsRouteChildren {
  InternshipsCorporateRoute: typeof InternshipsCorporateRoute
  InternshipsPrepRoute: typeof InternshipsPrepRoute
  InternshipsRemoteRoute: typeof InternshipsRemoteRoute
  InternshipsStartupRoute: typeof InternshipsStartupRoute
  InternshipsSummerRoute: typeof InternshipsSummerRoute
  InternshipsIndexRoute: typeof InternshipsIndexRoute
}

const InternshipsRouteChildren: InternshipsRouteChildren = {
  InternshipsCorporateRoute: InternshipsCorporateRoute,
  InternshipsPrepRoute: InternshipsPrepRoute,
  InternshipsRemoteRoute: InternshipsRemoteRoute,
  InternshipsStartupRoute: InternshipsStartupRoute,
  InternshipsSummerRoute: InternshipsSummerRoute,
  InternshipsIndexRoute: InternshipsIndexRoute,
}

const InternshipsRouteWithChildren = InternshipsRoute._addFileChildren(
  InternshipsRouteChildren,
)

interface MentorsRouteChildren {
  MentorsBecomeRoute: typeof MentorsBecomeRoute
  MentorsBookRoute: typeof MentorsBookRoute
  MentorsFindRoute: typeof MentorsFindRoute
  MentorsSessionsRoute: typeof MentorsSessionsRoute
  MentorsTopRoute: typeof MentorsTopRoute
  MentorsIndexRoute: typeof MentorsIndexRoute
}

const MentorsRouteChildren: MentorsRouteChildren = {
  MentorsBecomeRoute: MentorsBecomeRoute,
  MentorsBookRoute: MentorsBookRoute,
  MentorsFindRoute: MentorsFindRoute,
  MentorsSessionsRoute: MentorsSessionsRoute,
  MentorsTopRoute: MentorsTopRoute,
  MentorsIndexRoute: MentorsIndexRoute,
}

const MentorsRouteWithChildren =
  MentorsRoute._addFileChildren(MentorsRouteChildren)

interface RoadmapRouteChildren {
  RoadmapAiRoute: typeof RoadmapAiRoute
  RoadmapBusinessRoute: typeof RoadmapBusinessRoute
  RoadmapCreativeRoute: typeof RoadmapCreativeRoute
  RoadmapMilestonesRoute: typeof RoadmapMilestonesRoute
  RoadmapResourcesRoute: typeof RoadmapResourcesRoute
  RoadmapTechRoute: typeof RoadmapTechRoute
  RoadmapIndexRoute: typeof RoadmapIndexRoute
}

const RoadmapRouteChildren: RoadmapRouteChildren = {
  RoadmapAiRoute: RoadmapAiRoute,
  RoadmapBusinessRoute: RoadmapBusinessRoute,
  RoadmapCreativeRoute: RoadmapCreativeRoute,
  RoadmapMilestonesRoute: RoadmapMilestonesRoute,
  RoadmapResourcesRoute: RoadmapResourcesRoute,
  RoadmapTechRoute: RoadmapTechRoute,
  RoadmapIndexRoute: RoadmapIndexRoute,
}

const RoadmapRouteWithChildren =
  RoadmapRoute._addFileChildren(RoadmapRouteChildren)

interface ScholarshipsRouteChildren {
  ScholarshipsAbroadRoute: typeof ScholarshipsAbroadRoute
  ScholarshipsBrowseRoute: typeof ScholarshipsBrowseRoute
  ScholarshipsDiversityRoute: typeof ScholarshipsDiversityRoute
  ScholarshipsMeritRoute: typeof ScholarshipsMeritRoute
  ScholarshipsNeedRoute: typeof ScholarshipsNeedRoute
  ScholarshipsIndexRoute: typeof ScholarshipsIndexRoute
}

const ScholarshipsRouteChildren: ScholarshipsRouteChildren = {
  ScholarshipsAbroadRoute: ScholarshipsAbroadRoute,
  ScholarshipsBrowseRoute: ScholarshipsBrowseRoute,
  ScholarshipsDiversityRoute: ScholarshipsDiversityRoute,
  ScholarshipsMeritRoute: ScholarshipsMeritRoute,
  ScholarshipsNeedRoute: ScholarshipsNeedRoute,
  ScholarshipsIndexRoute: ScholarshipsIndexRoute,
}

const ScholarshipsRouteWithChildren = ScholarshipsRoute._addFileChildren(
  ScholarshipsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  AssessmentRoute: AssessmentRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CareerUniverseRoute: CareerUniverseRoute,
  CompareRoute: CompareRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EmailPreviewRoute: EmailPreviewRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  InternshipsRoute: InternshipsRouteWithChildren,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  MentorsRoute: MentorsRouteWithChildren,
  PersonalityRoute: PersonalityRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  ResumeRoute: ResumeRoute,
  RoadmapRoute: RoadmapRouteWithChildren,
  ScholarshipsRoute: ScholarshipsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkillsRoute: SkillsRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  WorkspaceRoute: WorkspaceRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  ApplyJobIdRoute: ApplyJobIdRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CareerSlugRoute: CareerSlugRoute,
  DomainSlugRoute: DomainSlugRoute,
  PlanIdRoute: PlanIdRoute,
  StreamIdRoute: StreamIdRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
